// Code generated by protoc-gen-go.
// source: pkg/protobuf/team/team.proto
// DO NOT EDIT!

/*
Package team is a generated protocol buffer package.

It is generated from these files:
	pkg/protobuf/team/team.proto

It has these top-level messages:
	CreateRequest
	AddUserRequest
	ListResponse
	Empty
*/
package team

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Url   string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AddUserRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	User string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *AddUserRequest) Reset()                    { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()               {}
func (*AddUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddUserRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type ListResponse struct {
	Teams []*ListResponse_Team `protobuf:"bytes,1,rep,name=teams" json:"teams,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListResponse) GetTeams() []*ListResponse_Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type ListResponse_User struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *ListResponse_User) Reset()                    { *m = ListResponse_User{} }
func (m *ListResponse_User) String() string            { return proto.CompactTextString(m) }
func (*ListResponse_User) ProtoMessage()               {}
func (*ListResponse_User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *ListResponse_User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ListResponse_Team struct {
	Name  string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string               `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Url   string               `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Users []*ListResponse_User `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
}

func (m *ListResponse_Team) Reset()                    { *m = ListResponse_Team{} }
func (m *ListResponse_Team) String() string            { return proto.CompactTextString(m) }
func (*ListResponse_Team) ProtoMessage()               {}
func (*ListResponse_Team) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *ListResponse_Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse_Team) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ListResponse_Team) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ListResponse_Team) GetUsers() []*ListResponse_User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "team.CreateRequest")
	proto.RegisterType((*AddUserRequest)(nil), "team.AddUserRequest")
	proto.RegisterType((*ListResponse)(nil), "team.ListResponse")
	proto.RegisterType((*ListResponse_User)(nil), "team.ListResponse.User")
	proto.RegisterType((*ListResponse_Team)(nil), "team.ListResponse.Team")
	proto.RegisterType((*Empty)(nil), "team.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Team service

type TeamClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Empty, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*Empty, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error)
}

type teamClient struct {
	cc *grpc.ClientConn
}

func NewTeamClient(cc *grpc.ClientConn) TeamClient {
	return &teamClient{cc}
}

func (c *teamClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/team.Team/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/team.Team/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/team.Team/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Team service

type TeamServer interface {
	Create(context.Context, *CreateRequest) (*Empty, error)
	AddUser(context.Context, *AddUserRequest) (*Empty, error)
	List(context.Context, *Empty) (*ListResponse, error)
}

func RegisterTeamServer(s *grpc.Server, srv TeamServer) {
	s.RegisterService(&_Team_serviceDesc, srv)
}

func _Team_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.Team/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Team_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.Team/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Team_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.Team/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Team_serviceDesc = grpc.ServiceDesc{
	ServiceName: "team.Team",
	HandlerType: (*TeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Team_Create_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Team_AddUser_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Team_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protobuf/team/team.proto",
}

func init() { proto.RegisterFile("pkg/protobuf/team/team.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x59, 0xb3, 0x69, 0x71, 0xaa, 0x22, 0x63, 0xc1, 0x25, 0x78, 0x28, 0xb9, 0x58, 0x44,
	0x53, 0xa9, 0x17, 0xaf, 0x22, 0x9e, 0xf4, 0x14, 0xf4, 0x01, 0xb6, 0x74, 0x94, 0x62, 0xb7, 0x49,
	0x77, 0x37, 0x07, 0x1f, 0xc1, 0xd7, 0xf4, 0x49, 0x64, 0x67, 0x73, 0x48, 0x10, 0x45, 0xe8, 0x25,
	0xfc, 0xf9, 0xf9, 0x77, 0xe6, 0xcb, 0x9f, 0x85, 0xb3, 0xfa, 0xfd, 0x6d, 0x56, 0xdb, 0xca, 0x57,
	0x8b, 0xe6, 0x75, 0xe6, 0x49, 0x1b, 0x7e, 0x14, 0x6c, 0xa1, 0x0c, 0x3a, 0x7f, 0x84, 0xc3, 0x7b,
	0x4b, 0xda, 0x53, 0x49, 0xdb, 0x86, 0x9c, 0x47, 0x04, 0xb9, 0xd1, 0x86, 0x94, 0x98, 0x88, 0xe9,
	0x7e, 0xc9, 0x1a, 0xc7, 0x90, 0x92, 0xd1, 0xab, 0xb5, 0xda, 0x63, 0x33, 0xbe, 0xe0, 0x31, 0x24,
	0x8d, 0x5d, 0xab, 0x84, 0xbd, 0x20, 0xf3, 0x5b, 0x38, 0xba, 0x5b, 0x2e, 0x5f, 0x1c, 0xd9, 0xbf,
	0xa6, 0x21, 0xc8, 0xc6, 0x91, 0x6d, 0x87, 0xb1, 0xce, 0xbf, 0x04, 0x1c, 0x3c, 0xad, 0x9c, 0x2f,
	0xc9, 0xd5, 0xd5, 0xc6, 0x11, 0x5e, 0x41, 0x1a, 0xf8, 0x9c, 0x12, 0x93, 0x64, 0x3a, 0x9a, 0x9f,
	0x16, 0x4c, 0xde, 0x8d, 0x14, 0xcf, 0xa4, 0x4d, 0x19, 0x53, 0xd9, 0x35, 0xc8, 0xb0, 0xf6, 0xff,
	0xf4, 0xd9, 0x16, 0x64, 0x18, 0xb0, 0xcb, 0xf7, 0x06, 0xc8, 0x40, 0xef, 0x94, 0xfc, 0x15, 0x92,
	0xcb, 0x88, 0xa9, 0x7c, 0x08, 0xe9, 0x83, 0xa9, 0xfd, 0xc7, 0xfc, 0x53, 0xb4, 0xcb, 0x2f, 0x60,
	0x10, 0xdb, 0xc7, 0x93, 0x78, 0xb6, 0xf7, 0x2f, 0xb2, 0x51, 0x34, 0xf9, 0x10, 0x5e, 0xc2, 0xb0,
	0x2d, 0x17, 0xc7, 0xd1, 0xef, 0x77, 0xdd, 0x4f, 0x9f, 0x83, 0x0c, 0x1c, 0xd8, 0x35, 0x33, 0xfc,
	0x09, 0xb8, 0x18, 0xf0, 0x6d, 0xb8, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x15, 0xeb, 0x5d, 0x54,
	0x2d, 0x02, 0x00, 0x00,
}
