package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserDetailsHandlerFunc turns a function with the right signature into a get user details handler
type GetUserDetailsHandlerFunc func(GetUserDetailsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserDetailsHandlerFunc) Handle(params GetUserDetailsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserDetailsHandler interface for that can handle valid get user details params
type GetUserDetailsHandler interface {
	Handle(GetUserDetailsParams, interface{}) middleware.Responder
}

// NewGetUserDetails creates a new http.Handler for the get user details operation
func NewGetUserDetails(ctx *middleware.Context, handler GetUserDetailsHandler) *GetUserDetails {
	return &GetUserDetails{Context: ctx, Handler: handler}
}

/*GetUserDetails swagger:route GET /users/{user_id} users getUserDetails

Get user details

Get user details

*/
type GetUserDetails struct {
	Context *middleware.Context
	Handler GetUserDetailsHandler
}

func (o *GetUserDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetUserDetailsParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
