# .goreleaser.yml
# Build customization
builds:
  - 
    main: cmd/client/main.go
    ldflags: -X pkg/version.Version=$(shell git describe --always --tags)
    binary: teresa
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
