language: go

go:
  - 1.9
  - tip

script:
  - ./.tests-run.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: helm
      before_script:
        - ./.helm.sh download
      script:
        - ./.helm.sh lint
      after_success:
        - ./.helm.sh deploy
    - stage: build docker image
      script:
        - ./.ci-docker.sh
    - stage: build and release client
      script:
        - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
        - export TMPDIR="$(mktemp -d)"
        - curl -sL http://git.io/goreleaser -o $TMPDIR/goreleaser.sh
        - chmod +x $TMPDIR/goreleaser.sh
        - $TMPDIR/goreleaser.sh --release-notes <(python release-notes.py)
