language: go

go:
  - 1.8
  - tip

before_script:
  - wget https://storage.googleapis.com/kubernetes-helm/helm-v2.5.1-linux-amd64.tar.gz /tmp/helm.tar.gz
  - tar -xcf /tmp/helm.tar.gz
  - export PATH=$PATH:$PWD/linux-amd64

script:
  - ./.tests-run.sh
  - 'if [ "$TRAVIS_PULL_REQUEST != "false" && $TRAVIS_GO_VERSION == "1.8" ]; then helm lint helm/chart/teresa; fi'

after_success:
  - bash <(curl -s https://codecov.io/bash)
