language: go

go:
  - 1.8
  - tip

jobs:
  include:
    - stage: helm
      before_script:
        - ./.helm.sh download
      script:
        - ./.helm.sh lint
      after_success:
        - ./.helm.sh deploy
    - stage: test
      script:
         - ./.tests-run.sh
      after_success:
        - bash <(curl -s https://codecov.io/bashl)
    - stage: build docker image
      script:
        - ./.ci-docker.sh
