language: go

go:
  - 1.8
  - tip

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

before_deploy:
  - make build-all-client

jobs:
  include:
    - stage: helm
      before_script:
        - ./.helm.sh download
      script:
        - ./.helm.sh lint
      after_success:
        - ./.helm.sh deploy
    - stage: build docker image
      script:
        - ./.ci-docker.sh
