language: go

go:
  - 1.8
  - tip

script:
  - ./.tests-run.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ -n "$TRAVIS_TAG" && "$TRAVIS_GO_VERSION" == "1.8" ]; then ./.ci-docker.sh; fi

services:
  - docker
