language: go

go:
  - 1.8
  - tip

script:
  - ./.tests-run.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" -a "$TRAVIS_GO_VERSION" = "1.8" && ./.ci-docker.sh

services:
  - docker
