FROM golang:1.6

RUN mkdir -p /go/src/github.com/luizalabs/tapi
WORKDIR /go/src/github.com/luizalabs/tapi
COPY . /go/src/github.com/luizalabs/tapi

RUN go get github.com/tools/godep
RUN godep go install ./cmd/teresa-server/...

ENV TERESAK8S_HOST $TERESAK8S_HOST
ENV TERESAK8S_USERNAME $TERESAK8S_USERNAME
ENV TERESAK8S_PASSWORD $TERESAK8S_PASSWORD
ENV TERESAK8S_INSECURE $TERESAK8S_INSECURE
ENV TERESABUILDER_STORAGE_AWS_KEY $TERESABUILDER_STORAGE_AWS_KEY
ENV TERESABUILDER_STORAGE_AWS_SECRET $TERESABUILDER_STORAGE_AWS_SECRET
ENV TERESABUILDER_STORAGE_AWS_REGION $TERESABUILDER_STORAGE_AWS_REGION
ENV TERESABUILDER_STORAGE_AWS_BUCKET $TERESABUILDER_STORAGE_AWS_BUCKET
ENV TERESABUILDER_WAIT_POD_TIMEOUT $TERESABUILDER_WAIT_POD_TIMEOUT
ENV TERESABUILDER_WAIT_LB_TIMEOUT $TERESABUILDER_WAIT_LB_TIMEOUT

CMD ["teresa-server", "--port", "8080"]
EXPOSE 8080
