FROM golang:1.6

RUN mkdir -p /go/src/github.com/luizalabs/teresa-api
WORKDIR /go/src/github.com/luizalabs/teresa-api
COPY . /go/src/github.com/luizalabs/teresa-api

RUN go get github.com/tools/godep
RUN godep go install ./cmd/teresa-server/...

ENV TERESAK8S_HOST $TERESAK8S_HOST
ENV TERESAK8S_USERNAME $TERESAK8S_USERNAME
ENV TERESAK8S_PASSWORD $TERESAK8S_PASSWORD
ENV TERESAK8S_INSECURE $TERESAK8S_INSECURE
ENV TERESAFILESTORAGE_TYPE $TERESAFILESTORAGE_TYPE
ENV TERESAFILESTORAGE_AWS_KEY $TERESAFILESTORAGE_AWS_KEY
ENV TERESAFILESTORAGE_AWS_SECRET $TERESAFILESTORAGE_AWS_SECRET
ENV TERESAFILESTORAGE_AWS_REGION $TERESAFILESTORAGE_AWS_REGION
ENV TERESAFILESTORAGE_AWS_BUCKET $TERESAFILESTORAGE_AWS_BUCKET

CMD ["teresa-server", "--host", "0.0.0.0", "--port", "8080"]
EXPOSE 8080
