apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        component: "server"
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "fullname" . }}
      {{- end }}
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.docker.registry }}/{{ .Values.docker.image }}:{{ .Values.docker.tag }}"
        args:
          - run
        {{- if .Values.tls.crt }}
          - --tls
        {{- end }}
        {{- if .Values.debug }}
          - --debug
        {{- end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: TERESA_DB_DATABASE
          value: {{ .Values.db.name }}
        {{- if .Values.db.hostname }}
        - name: TERESA_DB_HOSTNAME
          value: {{ .Values.db.hostname }}
        {{- end }}
        {{- if .Values.db.password }}
        - name: TERESA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-database
              key: db_password
        {{- end }}
        {{- if .Values.db.username }}
        - name: TERESA_DB_USERNAME
          value: {{ .Values.db.username }}
        {{- end }}
        - name: TERESA_SECRETS_PRIVATE_KEY
          value: /etc/teresa-keys/teresa.rsa
        - name: TERESA_SECRETS_PUBLIC_KEY
          value: /etc/teresa-keys/teresa.rsa.pub
        - name: TERESA_STORAGE_TYPE
          value: {{ .Values.storage.type }}
        {{- if .Values.useMinio }}
        - name: TERESA_STORAGE_AWS_ENDPOINT
          value: {{ template "minio.fullname" . }}
        {{- else if .Values.aws.s3.endpoint }}
        - name: TERESA_STORAGE_AWS_ENDPOINT
          value: {{ quote .Values.aws.s3.endpoint }}
        {{- end }}
        - name: TERESA_STORAGE_AWS_BUCKET
          {{- if .Values.useMinio }}
          value: {{ .Values.minio.defaultBucket.name }}
          {{- else }}
          value: {{ .Values.aws.s3.bucket }}
          {{- end }}
        - name: TERESA_STORAGE_AWS_S3_FORCE_PATH_STYLE
          value: {{ quote .Values.aws.s3.force_path_style }}
        - name: TERESA_STORAGE_AWS_KEY
          valueFrom:
            secretKeyRef:
              {{- if .Values.useMinio }}
              name: {{ template "minio.fullname" . }}-user
              key: accesskey
              {{- else }}
              name: {{ template "fullname" . }}-aws
              key: access_key
              {{- end }}
        - name: TERESA_STORAGE_AWS_SECRET
          valueFrom:
            secretKeyRef:
              {{- if .Values.useMinio }}
              name: {{ template "minio.fullname" . }}-user
              key: secretkey
              {{- else }}
              name: {{ template "fullname" . }}-aws
              key: secret_key
              {{- end }}
        - name: TERESA_STORAGE_AWS_REGION
          value: {{ .Values.aws.region }}
        {{- if .Values.tls.crt }}
        - name: TERESA_SECRETS_TLS_CERT
          value: /etc/teresa/server.crt
        - name: TERESA_SECRETS_TLS_KEY
          value: /etc/teresa/server.key
        {{- end }}
        - name: TERESA_DEPLOY_BUILD_LIMIT_CPU
          value: {{ .Values.build.limits.cpu }}
        - name: TERESA_DEPLOY_BUILD_LIMIT_MEMORY
          value: {{ .Values.build.limits.memory }}
        - name: TERESA_K8S_INGRESS
          value: {{ .Values.apps.ingress }}
        - name: TERESA_K8S_DEFAULT_SERVICE_TYPE
          value: {{ .Values.apps.service_type }}
        volumeMounts:
        {{- if .Values.tls.crt }}
        - mountPath: /etc/teresa
          name: {{ template "fullname" . }}-tls
          readOnly: true
        {{- end }}
        - mountPath: /etc/teresa-keys
          name: {{ template "fullname" . }}-keys
          readOnly: true
      volumes:
      {{- if .Values.tls.crt }}
      - name: {{ template "fullname" . }}-tls
        secret:
          defaultMode: 420
          secretName: {{ template "fullname" . }}-tls
      {{- end }}
      - name: {{ template "fullname" . }}-keys
        secret:
          defaultMode: 420
          secretName: {{ template "fullname" . }}-keys
