apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname". }}-keys
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "server"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  teresa.rsa: {{ .Values.rsa.private }}
  teresa.rsa.pub: {{ .Values.rsa.public }}
