{{- if and .Values.aws.key.access .Values.aws.key.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname". }}-aws
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "server"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  access_key: {{ .Values.aws.key.access | b64enc }}
  secret_key: {{ .Values.aws.key.secret | b64enc }}
{{- end }}
