kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "server"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "server"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
