package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/luizalabs/paas/api/models"
)

// GetAppDetailsReader is a Reader for the GetAppDetails structure.
type GetAppDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAppDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAppDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAppDetailsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAppDetailsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAppDetailsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetAppDetailsOK creates a GetAppDetailsOK with default headers values
func NewGetAppDetailsOK() *GetAppDetailsOK {
	return &GetAppDetailsOK{}
}

/*GetAppDetailsOK handles this case with default header values.

App details
*/
type GetAppDetailsOK struct {
	Payload *models.AppProperties
}

func (o *GetAppDetailsOK) Error() string {
	return fmt.Sprintf("[GET /teams/{team_id}/apps/{app_id}][%d] getAppDetailsOK  %+v", 200, o.Payload)
}

func (o *GetAppDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppProperties)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppDetailsUnauthorized creates a GetAppDetailsUnauthorized with default headers values
func NewGetAppDetailsUnauthorized() *GetAppDetailsUnauthorized {
	return &GetAppDetailsUnauthorized{}
}

/*GetAppDetailsUnauthorized handles this case with default header values.

User not authorized
*/
type GetAppDetailsUnauthorized struct {
	Payload *models.Unauthorized
}

func (o *GetAppDetailsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /teams/{team_id}/apps/{app_id}][%d] getAppDetailsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAppDetailsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppDetailsForbidden creates a GetAppDetailsForbidden with default headers values
func NewGetAppDetailsForbidden() *GetAppDetailsForbidden {
	return &GetAppDetailsForbidden{}
}

/*GetAppDetailsForbidden handles this case with default header values.

User does not have the credentials to access this resource

*/
type GetAppDetailsForbidden struct {
	Payload *models.Unauthorized
}

func (o *GetAppDetailsForbidden) Error() string {
	return fmt.Sprintf("[GET /teams/{team_id}/apps/{app_id}][%d] getAppDetailsForbidden  %+v", 403, o.Payload)
}

func (o *GetAppDetailsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppDetailsDefault creates a GetAppDetailsDefault with default headers values
func NewGetAppDetailsDefault(code int) *GetAppDetailsDefault {
	return &GetAppDetailsDefault{
		_statusCode: code,
	}
}

/*GetAppDetailsDefault handles this case with default header values.

Error
*/
type GetAppDetailsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get app details default response
func (o *GetAppDetailsDefault) Code() int {
	return o._statusCode
}

func (o *GetAppDetailsDefault) Error() string {
	return fmt.Sprintf("[GET /teams/{team_id}/apps/{app_id}][%d] getAppDetails default  %+v", o._statusCode, o.Payload)
}

func (o *GetAppDetailsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
