package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTeamsParams creates a new GetTeamsParams object
// with the default values initialized.
func NewGetTeamsParams() *GetTeamsParams {
	var (
		limitDefault int64 = int64(20)
		sinceDefault int64 = int64(0)
	)
	return &GetTeamsParams{
		Limit: &limitDefault,
		Since: &sinceDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTeamsParamsWithTimeout creates a new GetTeamsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTeamsParamsWithTimeout(timeout time.Duration) *GetTeamsParams {
	var (
		limitDefault int64 = int64(20)
		sinceDefault int64 = int64(0)
	)
	return &GetTeamsParams{
		Limit: &limitDefault,
		Since: &sinceDefault,

		timeout: timeout,
	}
}

/*GetTeamsParams contains all the parameters to send to the API endpoint
for the get teams operation typically these are written to a http.Request
*/
type GetTeamsParams struct {

	/*Limit
	  Limit

	*/
	Limit *int64
	/*Since
	  Offset

	*/
	Since *int64

	timeout time.Duration
}

// WithLimit adds the limit to the get teams params
func (o *GetTeamsParams) WithLimit(Limit *int64) *GetTeamsParams {
	o.Limit = Limit
	return o
}

// WithSince adds the since to the get teams params
func (o *GetTeamsParams) WithSince(Since *int64) *GetTeamsParams {
	o.Since = Since
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetTeamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Since != nil {

		// query param since
		var qrSince int64
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
