package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCurrentUserParams creates a new GetCurrentUserParams object
// with the default values initialized.
func NewGetCurrentUserParams() *GetCurrentUserParams {

	return &GetCurrentUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserParamsWithTimeout creates a new GetCurrentUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCurrentUserParamsWithTimeout(timeout time.Duration) *GetCurrentUserParams {

	return &GetCurrentUserParams{

		timeout: timeout,
	}
}

/*GetCurrentUserParams contains all the parameters to send to the API endpoint
for the get current user operation typically these are written to a http.Request
*/
type GetCurrentUserParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
