package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAddUserToTeamParams creates a new AddUserToTeamParams object
// with the default values initialized.
func NewAddUserToTeamParams() AddUserToTeamParams {
	var ()
	return AddUserToTeamParams{}
}

// AddUserToTeamParams contains all the bound params for the add user to team operation
// typically these are obtained from a http.Request
//
// swagger:parameters addUserToTeam
type AddUserToTeamParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Team name
	  Required: true
	  Pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
	  In: path
	*/
	TeamName string
	/*
	  In: body
	*/
	User AddUserToTeamBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddUserToTeamParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rTeamName, rhkTeamName, _ := route.Params.GetOK("team_name")
	if err := o.bindTeamName(rTeamName, rhkTeamName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body AddUserToTeamBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("user", "body", "", err))
		} else {

			if len(res) == 0 {
				o.User = body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddUserToTeamParams) bindTeamName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.TeamName = raw

	if err := o.validateTeamName(formats); err != nil {
		return err
	}

	return nil
}

func (o *AddUserToTeamParams) validateTeamName(formats strfmt.Registry) error {

	if err := validate.Pattern("team_name", "path", string(o.TeamName), `^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`); err != nil {
		return err
	}

	return nil
}
