package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/luizalabs/tapi/models"
)

/*GetTeamDetailOK Team details

swagger:response getTeamDetailOK
*/
type GetTeamDetailOK struct {

	// In: body
	Payload *models.Team `json:"body,omitempty"`
}

// NewGetTeamDetailOK creates GetTeamDetailOK with default headers values
func NewGetTeamDetailOK() *GetTeamDetailOK {
	return &GetTeamDetailOK{}
}

// WithPayload adds the payload to the get team detail o k response
func (o *GetTeamDetailOK) WithPayload(payload *models.Team) *GetTeamDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get team detail o k response
func (o *GetTeamDetailOK) SetPayload(payload *models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTeamDetailUnauthorized User not authorized

swagger:response getTeamDetailUnauthorized
*/
type GetTeamDetailUnauthorized struct {

	// In: body
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewGetTeamDetailUnauthorized creates GetTeamDetailUnauthorized with default headers values
func NewGetTeamDetailUnauthorized() *GetTeamDetailUnauthorized {
	return &GetTeamDetailUnauthorized{}
}

// WithPayload adds the payload to the get team detail unauthorized response
func (o *GetTeamDetailUnauthorized) WithPayload(payload *models.Unauthorized) *GetTeamDetailUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get team detail unauthorized response
func (o *GetTeamDetailUnauthorized) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamDetailUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTeamDetailForbidden User does not have the credentials to access this resource


swagger:response getTeamDetailForbidden
*/
type GetTeamDetailForbidden struct {

	// In: body
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewGetTeamDetailForbidden creates GetTeamDetailForbidden with default headers values
func NewGetTeamDetailForbidden() *GetTeamDetailForbidden {
	return &GetTeamDetailForbidden{}
}

// WithPayload adds the payload to the get team detail forbidden response
func (o *GetTeamDetailForbidden) WithPayload(payload *models.Unauthorized) *GetTeamDetailForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get team detail forbidden response
func (o *GetTeamDetailForbidden) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamDetailForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTeamDetailDefault Error

swagger:response getTeamDetailDefault
*/
type GetTeamDetailDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTeamDetailDefault creates GetTeamDetailDefault with default headers values
func NewGetTeamDetailDefault(code int) *GetTeamDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTeamDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get team detail default response
func (o *GetTeamDetailDefault) WithStatusCode(code int) *GetTeamDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get team detail default response
func (o *GetTeamDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get team detail default response
func (o *GetTeamDetailDefault) WithPayload(payload *models.Error) *GetTeamDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get team detail default response
func (o *GetTeamDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
