package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/luizalabs/teresa/api/models"
)

/*DeleteTeamNoContent No content

swagger:response deleteTeamNoContent
*/
type DeleteTeamNoContent struct {
}

// NewDeleteTeamNoContent creates DeleteTeamNoContent with default headers values
func NewDeleteTeamNoContent() *DeleteTeamNoContent {
	return &DeleteTeamNoContent{}
}

// WriteResponse to the client
func (o *DeleteTeamNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*DeleteTeamDefault Error

swagger:response deleteTeamDefault
*/
type DeleteTeamDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTeamDefault creates DeleteTeamDefault with default headers values
func NewDeleteTeamDefault(code int) *DeleteTeamDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTeamDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete team default response
func (o *DeleteTeamDefault) WithStatusCode(code int) *DeleteTeamDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete team default response
func (o *DeleteTeamDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete team default response
func (o *DeleteTeamDefault) WithPayload(payload *models.Error) *DeleteTeamDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete team default response
func (o *DeleteTeamDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTeamDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
