package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserDetailsParams creates a new GetUserDetailsParams object
// with the default values initialized.
func NewGetUserDetailsParams() *GetUserDetailsParams {
	var (
		limitDefault = int64(20)
		sinceDefault = int64(0)
	)
	return &GetUserDetailsParams{
		Limit: &limitDefault,
		Since: &sinceDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserDetailsParamsWithTimeout creates a new GetUserDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserDetailsParamsWithTimeout(timeout time.Duration) *GetUserDetailsParams {
	var (
		limitDefault int64 = int64(20)
		sinceDefault int64 = int64(0)
	)
	return &GetUserDetailsParams{
		Limit: &limitDefault,
		Since: &sinceDefault,

		timeout: timeout,
	}
}

/*GetUserDetailsParams contains all the parameters to send to the API endpoint
for the get user details operation typically these are written to a http.Request
*/
type GetUserDetailsParams struct {

	/*Limit
	  Limit

	*/
	Limit *int64
	/*Since
	  Offset

	*/
	Since *int64
	/*UserID
	  User ID

	*/
	UserID int64

	timeout time.Duration
}

// WithLimit adds the limit to the get user details params
func (o *GetUserDetailsParams) WithLimit(limit *int64) *GetUserDetailsParams {
	o.Limit = limit
	return o
}

// WithSince adds the since to the get user details params
func (o *GetUserDetailsParams) WithSince(since *int64) *GetUserDetailsParams {
	o.Since = since
	return o
}

// WithUserID adds the userID to the get user details params
func (o *GetUserDetailsParams) WithUserID(userID int64) *GetUserDetailsParams {
	o.UserID = userID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Since != nil {

		// query param since
		var qrSince int64
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
