// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protobuf/service/service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	pkg/protobuf/service/service.proto

It has these top-level messages:
	EnableSSLRequest
	Empty
	InfoRequest
	InfoResponse
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnableSSLRequest struct {
	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	Cert    string `protobuf:"bytes,2,opt,name=cert" json:"cert,omitempty"`
	Only    bool   `protobuf:"varint,3,opt,name=only" json:"only,omitempty"`
}

func (m *EnableSSLRequest) Reset()                    { *m = EnableSSLRequest{} }
func (m *EnableSSLRequest) String() string            { return proto.CompactTextString(m) }
func (*EnableSSLRequest) ProtoMessage()               {}
func (*EnableSSLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EnableSSLRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *EnableSSLRequest) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *EnableSSLRequest) GetOnly() bool {
	if m != nil {
		return m.Only
	}
	return false
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type InfoRequest struct {
	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InfoRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type InfoResponse struct {
	ServicePorts []*InfoResponse_ServicePort `protobuf:"bytes,1,rep,name=service_ports,json=servicePorts" json:"service_ports,omitempty"`
	Ssl          *InfoResponse_SSL           `protobuf:"bytes,2,opt,name=ssl" json:"ssl,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InfoResponse) GetServicePorts() []*InfoResponse_ServicePort {
	if m != nil {
		return m.ServicePorts
	}
	return nil
}

func (m *InfoResponse) GetSsl() *InfoResponse_SSL {
	if m != nil {
		return m.Ssl
	}
	return nil
}

type InfoResponse_ServicePort struct {
	Port int32 `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
}

func (m *InfoResponse_ServicePort) Reset()                    { *m = InfoResponse_ServicePort{} }
func (m *InfoResponse_ServicePort) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_ServicePort) ProtoMessage()               {}
func (*InfoResponse_ServicePort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *InfoResponse_ServicePort) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type InfoResponse_SSL struct {
	ServicePort *InfoResponse_ServicePort `protobuf:"bytes,1,opt,name=service_port,json=servicePort" json:"service_port,omitempty"`
	Cert        string                    `protobuf:"bytes,2,opt,name=cert" json:"cert,omitempty"`
}

func (m *InfoResponse_SSL) Reset()                    { *m = InfoResponse_SSL{} }
func (m *InfoResponse_SSL) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_SSL) ProtoMessage()               {}
func (*InfoResponse_SSL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 1} }

func (m *InfoResponse_SSL) GetServicePort() *InfoResponse_ServicePort {
	if m != nil {
		return m.ServicePort
	}
	return nil
}

func (m *InfoResponse_SSL) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func init() {
	proto.RegisterType((*EnableSSLRequest)(nil), "service.EnableSSLRequest")
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*InfoRequest)(nil), "service.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "service.InfoResponse")
	proto.RegisterType((*InfoResponse_ServicePort)(nil), "service.InfoResponse.ServicePort")
	proto.RegisterType((*InfoResponse_SSL)(nil), "service.InfoResponse.SSL")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	EnableSSL(ctx context.Context, in *EnableSSLRequest, opts ...grpc.CallOption) (*Empty, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) EnableSSL(ctx context.Context, in *EnableSSLRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/service.Service/EnableSSL", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/service.Service/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	EnableSSL(context.Context, *EnableSSLRequest) (*Empty, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_EnableSSL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableSSLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).EnableSSL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/EnableSSL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).EnableSSL(ctx, req.(*EnableSSLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableSSL",
			Handler:    _Service_EnableSSL_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Service_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protobuf/service/service.proto",
}

func init() { proto.RegisterFile("pkg/protobuf/service/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x49, 0xd3, 0x9a, 0x76, 0x52, 0x45, 0x06, 0x85, 0xb4, 0xa7, 0x36, 0xa7, 0x80, 0x90,
	0x42, 0x0a, 0x3e, 0x81, 0x15, 0x84, 0x20, 0xb2, 0x8b, 0xe7, 0x90, 0x94, 0xad, 0x88, 0x49, 0x76,
	0xcd, 0x6e, 0x0b, 0x7d, 0x02, 0x5f, 0x5b, 0x76, 0x93, 0x9a, 0x18, 0x14, 0x3d, 0x65, 0x3e, 0xfe,
	0x99, 0xf9, 0xcd, 0xcc, 0x82, 0x2f, 0xde, 0x5e, 0x56, 0xa2, 0xe2, 0x8a, 0x67, 0xfb, 0xdd, 0x4a,
	0xb2, 0xea, 0xf0, 0xba, 0x65, 0xa7, 0x6f, 0x68, 0x12, 0xe8, 0x34, 0xae, 0xff, 0x0c, 0x97, 0x9b,
	0x32, 0xcd, 0x72, 0x46, 0x69, 0x4c, 0xd8, 0xfb, 0x9e, 0x49, 0x85, 0x33, 0x18, 0xa7, 0x42, 0x24,
	0x65, 0x5a, 0x30, 0xcf, 0x5a, 0x58, 0xc1, 0x84, 0x38, 0xa9, 0x10, 0x8f, 0x69, 0xc1, 0x10, 0x61,
	0xb8, 0x65, 0x95, 0xf2, 0x06, 0x26, 0x6c, 0x6c, 0x1d, 0xe3, 0x65, 0x7e, 0xf4, 0xec, 0x85, 0x15,
	0x8c, 0x89, 0xb1, 0x7d, 0x07, 0x46, 0x9b, 0x42, 0xa8, 0xa3, 0x1f, 0x80, 0xfb, 0x50, 0xee, 0xf8,
	0xdf, 0xa5, 0xfd, 0x8f, 0x01, 0x4c, 0x6b, 0xa9, 0x14, 0xbc, 0x94, 0x0c, 0xef, 0xe1, 0xbc, 0xa1,
	0x4c, 0x04, 0xaf, 0x94, 0xf4, 0xac, 0x85, 0x1d, 0xb8, 0xd1, 0x32, 0x3c, 0x8d, 0xd2, 0x55, 0x87,
	0xb4, 0x0e, 0x3e, 0xf1, 0x4a, 0x91, 0xa9, 0x6c, 0x1d, 0x89, 0x37, 0x60, 0x4b, 0x99, 0x1b, 0x64,
	0x37, 0x9a, 0xfd, 0xf2, 0x37, 0x8d, 0x89, 0x56, 0xcd, 0x97, 0xe0, 0x76, 0x2a, 0xe9, 0xd9, 0x74,
	0x6f, 0xc3, 0x3a, 0x22, 0xc6, 0x9e, 0x27, 0x60, 0x53, 0x1a, 0xe3, 0x1d, 0x4c, 0xbb, 0x78, 0x46,
	0xf2, 0x2f, 0x3a, 0x57, 0x7e, 0x6f, 0xd0, 0x5f, 0x68, 0x74, 0x00, 0xa7, 0xd1, 0xe3, 0x2d, 0x4c,
	0xbe, 0xce, 0x83, 0x2d, 0x7b, 0xff, 0x64, 0xf3, 0x8b, 0x36, 0xa5, 0xd7, 0x8e, 0x6b, 0x18, 0xea,
	0xfe, 0x78, 0xd5, 0xc3, 0xa9, 0xd5, 0xd7, 0x3f, 0x42, 0x66, 0x67, 0xe6, 0x6d, 0xac, 0x3f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xb9, 0xd1, 0x74, 0xb5, 0x41, 0x02, 0x00, 0x00,
}
