package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateAppHandlerFunc turns a function with the right signature into a create app handler
type CreateAppHandlerFunc func(CreateAppParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAppHandlerFunc) Handle(params CreateAppParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateAppHandler interface for that can handle valid create app params
type CreateAppHandler interface {
	Handle(CreateAppParams, interface{}) middleware.Responder
}

// NewCreateApp creates a new http.Handler for the create app operation
func NewCreateApp(ctx *middleware.Context, handler CreateAppHandler) *CreateApp {
	return &CreateApp{Context: ctx, Handler: handler}
}

/*CreateApp swagger:route POST /teams/{team_id}/apps apps createApp

Create an app

Create an app

*/
type CreateApp struct {
	Context *middleware.Context
	Handler CreateAppHandler
}

func (o *CreateApp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewCreateAppParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
