package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAppLogsHandlerFunc turns a function with the right signature into a get app logs handler
type GetAppLogsHandlerFunc func(GetAppLogsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppLogsHandlerFunc) Handle(params GetAppLogsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAppLogsHandler interface for that can handle valid get app logs params
type GetAppLogsHandler interface {
	Handle(GetAppLogsParams, interface{}) middleware.Responder
}

// NewGetAppLogs creates a new http.Handler for the get app logs operation
func NewGetAppLogs(ctx *middleware.Context, handler GetAppLogsHandler) *GetAppLogs {
	return &GetAppLogs{Context: ctx, Handler: handler}
}

/*GetAppLogs swagger:route GET /apps/{app_name}/logs apps getAppLogs

Get app logs

Get app logs

*/
type GetAppLogs struct {
	Context *middleware.Context
	Handler GetAppLogsHandler
}

func (o *GetAppLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetAppLogsParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
