package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/luizalabs/teresa-api/models"
)

/*GetAppsOK Apps

swagger:response getAppsOK
*/
type GetAppsOK struct {

	// In: body
	Payload GetAppsOKBodyBody `json:"body,omitempty"`
}

// NewGetAppsOK creates GetAppsOK with default headers values
func NewGetAppsOK() *GetAppsOK {
	return &GetAppsOK{}
}

// WithPayload adds the payload to the get apps o k response
func (o *GetAppsOK) WithPayload(payload GetAppsOKBodyBody) *GetAppsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get apps o k response
func (o *GetAppsOK) SetPayload(payload GetAppsOKBodyBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetAppsUnauthorized User not authorized

swagger:response getAppsUnauthorized
*/
type GetAppsUnauthorized struct {

	// In: body
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewGetAppsUnauthorized creates GetAppsUnauthorized with default headers values
func NewGetAppsUnauthorized() *GetAppsUnauthorized {
	return &GetAppsUnauthorized{}
}

// WithPayload adds the payload to the get apps unauthorized response
func (o *GetAppsUnauthorized) WithPayload(payload *models.Unauthorized) *GetAppsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get apps unauthorized response
func (o *GetAppsUnauthorized) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAppsForbidden User does not have the credentials to access this resource


swagger:response getAppsForbidden
*/
type GetAppsForbidden struct {

	// In: body
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewGetAppsForbidden creates GetAppsForbidden with default headers values
func NewGetAppsForbidden() *GetAppsForbidden {
	return &GetAppsForbidden{}
}

// WithPayload adds the payload to the get apps forbidden response
func (o *GetAppsForbidden) WithPayload(payload *models.Unauthorized) *GetAppsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get apps forbidden response
func (o *GetAppsForbidden) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAppsDefault Error

swagger:response getAppsDefault
*/
type GetAppsDefault struct {
	_statusCode int

	// In: body
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewGetAppsDefault creates GetAppsDefault with default headers values
func NewGetAppsDefault(code int) *GetAppsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAppsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get apps default response
func (o *GetAppsDefault) WithStatusCode(code int) *GetAppsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get apps default response
func (o *GetAppsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get apps default response
func (o *GetAppsDefault) WithPayload(payload *models.GenericError) *GetAppsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get apps default response
func (o *GetAppsDefault) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
