package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateAppAutoScaleHandlerFunc turns a function with the right signature into a update app auto scale handler
type UpdateAppAutoScaleHandlerFunc func(UpdateAppAutoScaleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateAppAutoScaleHandlerFunc) Handle(params UpdateAppAutoScaleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateAppAutoScaleHandler interface for that can handle valid update app auto scale params
type UpdateAppAutoScaleHandler interface {
	Handle(UpdateAppAutoScaleParams, interface{}) middleware.Responder
}

// NewUpdateAppAutoScale creates a new http.Handler for the update app auto scale operation
func NewUpdateAppAutoScale(ctx *middleware.Context, handler UpdateAppAutoScaleHandler) *UpdateAppAutoScale {
	return &UpdateAppAutoScale{Context: ctx, Handler: handler}
}

/*UpdateAppAutoScale swagger:route PUT /apps/{app_name}/autoScale apps updateAppAutoScale

Update app auto scale

Update app auto scale

*/
type UpdateAppAutoScale struct {
	Context *middleware.Context
	Handler UpdateAppAutoScaleHandler
}

func (o *UpdateAppAutoScale) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateAppAutoScaleParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
