package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/luizalabs/teresa-api/models"
)

/*UpdateAppAutoScaleOK Updated version of the app

swagger:response updateAppAutoScaleOK
*/
type UpdateAppAutoScaleOK struct {

	// In: body
	Payload *models.App `json:"body,omitempty"`
}

// NewUpdateAppAutoScaleOK creates UpdateAppAutoScaleOK with default headers values
func NewUpdateAppAutoScaleOK() *UpdateAppAutoScaleOK {
	return &UpdateAppAutoScaleOK{}
}

// WithPayload adds the payload to the update app auto scale o k response
func (o *UpdateAppAutoScaleOK) WithPayload(payload *models.App) *UpdateAppAutoScaleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update app auto scale o k response
func (o *UpdateAppAutoScaleOK) SetPayload(payload *models.App) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateAppAutoScaleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateAppAutoScaleDefault Unexpected error

swagger:response updateAppAutoScaleDefault
*/
type UpdateAppAutoScaleDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateAppAutoScaleDefault creates UpdateAppAutoScaleDefault with default headers values
func NewUpdateAppAutoScaleDefault(code int) *UpdateAppAutoScaleDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateAppAutoScaleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update app auto scale default response
func (o *UpdateAppAutoScaleDefault) WithStatusCode(code int) *UpdateAppAutoScaleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update app auto scale default response
func (o *UpdateAppAutoScaleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update app auto scale default response
func (o *UpdateAppAutoScaleDefault) WithPayload(payload *models.Error) *UpdateAppAutoScaleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update app auto scale default response
func (o *UpdateAppAutoScaleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateAppAutoScaleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
