package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/luizalabs/teresa-api/models"
)

// NewUpdateAppAutoScaleParams creates a new UpdateAppAutoScaleParams object
// with the default values initialized.
func NewUpdateAppAutoScaleParams() UpdateAppAutoScaleParams {
	var ()
	return UpdateAppAutoScaleParams{}
}

// UpdateAppAutoScaleParams contains all the bound params for the update app auto scale operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateAppAutoScale
type UpdateAppAutoScaleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*App name
	  Required: true
	  Pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
	  In: path
	*/
	AppName string
	/*
	  Required: true
	  In: body
	*/
	Body *models.AutoScale
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateAppAutoScaleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rAppName, rhkAppName, _ := route.Params.GetOK("app_name")
	if err := o.bindAppName(rAppName, rhkAppName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.AutoScale
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateAppAutoScaleParams) bindAppName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.AppName = raw

	if err := o.validateAppName(formats); err != nil {
		return err
	}

	return nil
}

func (o *UpdateAppAutoScaleParams) validateAppName(formats strfmt.Registry) error {

	if err := validate.Pattern("app_name", "path", string(o.AppName), `^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`); err != nil {
		return err
	}

	return nil
}
