package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/luizalabs/teresa-api/models"
)

// PartialUpdateAppReader is a Reader for the PartialUpdateApp structure.
type PartialUpdateAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PartialUpdateAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPartialUpdateAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPartialUpdateAppDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPartialUpdateAppOK creates a PartialUpdateAppOK with default headers values
func NewPartialUpdateAppOK() *PartialUpdateAppOK {
	return &PartialUpdateAppOK{}
}

/*PartialUpdateAppOK handles this case with default header values.

App
*/
type PartialUpdateAppOK struct {
	Payload *models.App
}

func (o *PartialUpdateAppOK) Error() string {
	return fmt.Sprintf("[PATCH /apps/{app_name}][%d] partialUpdateAppOK  %+v", 200, o.Payload)
}

func (o *PartialUpdateAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.App)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartialUpdateAppDefault creates a PartialUpdateAppDefault with default headers values
func NewPartialUpdateAppDefault(code int) *PartialUpdateAppDefault {
	return &PartialUpdateAppDefault{
		_statusCode: code,
	}
}

/*PartialUpdateAppDefault handles this case with default header values.

Unexpected error
*/
type PartialUpdateAppDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the partial update app default response
func (o *PartialUpdateAppDefault) Code() int {
	return o._statusCode
}

func (o *PartialUpdateAppDefault) Error() string {
	return fmt.Sprintf("[PATCH /apps/{app_name}][%d] partialUpdateApp default  %+v", o._statusCode, o.Payload)
}

func (o *PartialUpdateAppDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
