package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteTeamParams creates a new DeleteTeamParams object
// with the default values initialized.
func NewDeleteTeamParams() *DeleteTeamParams {
	var ()
	return &DeleteTeamParams{}
}

/*DeleteTeamParams contains all the parameters to send to the API endpoint
for the delete team operation typically these are written to a http.Request
*/
type DeleteTeamParams struct {

	/*TeamID
	  Team ID

	*/
	TeamID int64
}

// WithTeamID adds the teamId to the delete team params
func (o *DeleteTeamParams) WithTeamID(TeamID int64) *DeleteTeamParams {
	o.TeamID = TeamID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTeamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param team_id
	if err := r.SetPathParam("team_id", swag.FormatInt64(o.TeamID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
