package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/luizalabs/teresa-api/models"
)

// GetTeamsReader is a Reader for the GetTeams structure.
type GetTeamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetTeamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTeamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetTeamsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetTeamsOK creates a GetTeamsOK with default headers values
func NewGetTeamsOK() *GetTeamsOK {
	return &GetTeamsOK{}
}

/*GetTeamsOK handles this case with default header values.

list of teams
*/
type GetTeamsOK struct {
	Payload []*models.Team
}

func (o *GetTeamsOK) Error() string {
	return fmt.Sprintf("[GET /teams][%d] getTeamsOK  %+v", 200, o.Payload)
}

func (o *GetTeamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTeamsDefault creates a GetTeamsDefault with default headers values
func NewGetTeamsDefault(code int) *GetTeamsDefault {
	return &GetTeamsDefault{
		_statusCode: code,
	}
}

/*GetTeamsDefault handles this case with default header values.

Unexpected error
*/
type GetTeamsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get teams default response
func (o *GetTeamsDefault) Code() int {
	return o._statusCode
}

func (o *GetTeamsDefault) Error() string {
	return fmt.Sprintf("[GET /teams][%d] getTeams default  %+v", o._statusCode, o.Payload)
}

func (o *GetTeamsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
