package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*App app

swagger:model App
*/
type App struct {

	/* deploy list
	 */
	DeployList []*Deployment `json:"deployList,omitempty"`

	/* id
	 */
	ID int64 `json:"id,omitempty"`

	/* name
	 */
	Name string `json:"name,omitempty"`
}

// Validate validates this app
func (m *App) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeployList(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *App) validateDeployList(formats strfmt.Registry) error {

	if swag.IsZero(m.DeployList) { // not required
		return nil
	}

	return nil
}
