package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*PatchAppEnvVar app environment var

swagger:model PatchAppEnvVar
*/
type PatchAppEnvVar struct {

	/* key

	Required: true
	*/
	Key *string `json:"key"`

	/* value
	 */
	Value string `json:"value,omitempty"`
}

// Validate validates this patch app env var
func (m *PatchAppEnvVar) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchAppEnvVar) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	return nil
}
