package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*Status status

swagger:model Status
*/
type Status struct {

	/* cpu

	Required: true
	*/
	CPU *int32 `json:"cpu"`

	/* pods

	Required: true
	*/
	Pods *int32 `json:"pods"`
}

// Validate validates this status
func (m *Status) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCPU(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePods(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Status) validateCPU(formats strfmt.Registry) error {

	if err := validate.Required("cpu", "body", m.CPU); err != nil {
		return err
	}

	return nil
}

func (m *Status) validatePods(formats strfmt.Registry) error {

	if err := validate.Required("pods", "body", m.Pods); err != nil {
		return err
	}

	return nil
}
